#email to which errors will be sent
email: ""
#Location of the config file for BarcodeIdentification
bID: "example_config.txt"
#Location of the format file for barcode filtering
format: "example_format.txt"
#Location of the samples json file produced with the fastq2json.py script 
samples: "samples.json"
#Output directory  
output_dir: ""
#Temporary directory
temp_dir: "/central/scratch/"
#Currently "mm10" and "hg38" available
assembly: "mm10"
#Number of barcodes used
num_tags: "7"
#Number of chunks to split fastq
num_chunks: "20"
#Files for cutadapt
cutadapt_dpm: "assets/dpm96.fasta"
cutadapt_oligos: "assets/bpm.fasta"
#Repeat mask used for filtering DNA reads
mask:
    mm10: "assets/blacklist_mm10.bed"
    hg38: "assets/blacklist_hg38.bed"
#Bowtie2 Indexes for aligning DNA reads
bowtie2_index:
    mm10: "assets/index_mm10/mm10"
    hg38: "assets/index_hg38/GRCh38_noalt_as"
#Bamfile generation for individual targets
generate_splitbams: "True"
min_oligos: "2"
proportion: "0.8"
max_size: "10000"
