# Email to which errors will be sent; set to null or "" to skip emails
email: ""

# (Required) Path to barcode config file
barcode_config: "example_config.txt"

# Path to barcode format file; set to null or "" to skip barcode validation
barcode_format: "example_format.txt"

# (Required) Path to samples JSON file, e.g., as produced with the fastq2json.py script
samples: "example_samples.json"

# (Required) Scripts directory
scripts_dir: "scripts/"

# Output directory
output_dir: ""

# Temporary directory
temp_dir: "/central/scratch/"

# Conda environment: either a path to a conda environment YAML file ("*.yml" or "*.yaml")
# or the name of an existing conda environment
conda_env: "envs/chipdip.yaml"

# Path to chromosome name map file; set to null or "" to skip chromosome renaming and filtering
path_chrom_map: "chrom_map.txt"

# Number of chunks to split FASTQ reads into for parallel processing
num_chunks: 2

# (Required) Files for cutadapt
cutadapt_dpm: "assets/dpm96.fasta"
cutadapt_oligos: "assets/bpm.fasta"

# (Required) Bead oligo UMI length
bead_umi_length: 8

# Mask used for filtering DNA reads
# e.g., "assets/blacklist_mm10.bed" or "assets/blacklist_hg38.bed"
# Set to null or "" to skip filtering
mask: "assets/blacklist_mm10.bed"

# (Required) Bowtie2 indexes for aligning DNA reads
# e.g., "assets/index_hg38/GRCh38_noalt_as" or "assets/index_mm10/mm10"
bowtie2_index: "assets/index_mm10/mm10"

# Merge cluster files for all samples
# Merge BAM files and bigWigs for individual targets across samples
merge_samples: true

# Generate BAM files for individual targets
generate_splitbams: true
min_oligos: 2
proportion: 0.8
max_size: 10000

# bigWig generation parameters
# - only relevant if generate_splitbams is True
# - binsize: bin size in bp
#   - Set to false to skip bigWig generation
# - bigwig_normalization: "RPKM", "CPM", "BPM", "RPGC", or "None"
#   - Passed to the --normalizeUsing argument for bamCoverage from the deepTools suite
# - effective_genome_size: effective genome size in bp
#   - only relevant if bigwig_normalization is "RPGC"
#   - Supply as an integer, or set to null for the pipeline to compute the effective genome size
#     based on the Bowtie2 index, mask, and chromosome name map
binsize: 1000
bigwig_normalization: "None"
effective_genome_size: null
