# Email to which errors will be sent
email: ""
# Path to barcoding config file
bID: "example_config.txt"
# Path to barcoding format file
format: "example_format.txt"
# Path to samples JSON file, e.g., as produced with the fastq2json.py script
samples: "example_samples.json"
# Scripts directory
scripts_dir: "scripts/"
# Output directory
output_dir: ""
# Temporary directory
temp_dir: "/central/scratch/"
# Use existing conda environment named chipdip
use_existing_conda_env: false
# Currently "mm10" and "hg38" available
assembly: "mm10"
# Number of rounds of tags used, including DPM
num_tags: 7
# Number of chunks to split FASTQ reads into for parallel processing
num_chunks: 2
# Files for cutadapt
cutadapt_dpm: "assets/dpm96.fasta"
cutadapt_oligos: "assets/bpm.fasta"
# Mask used for filtering DNA reads
mask:
    mm10: "assets/blacklist_mm10.bed"
    hg38: "assets/blacklist_hg38.bed"
# Bowtie2 indexes for aligning DNA reads
bowtie2_index:
    mm10: "assets/index_mm10/mm10"
    hg38: "assets/index_hg38/GRCh38_noalt_as"
# Generate BAM files for individual targets
generate_splitbams: true
min_oligos: 2
proportion: 0.8
max_size: 10000
# Merge and index split BAM files across samples
merge_and_index_splitbams: true
