software-deployment-method: conda
conda-frontend: conda
executor: slurm
jobs: 100
latency-wait: 60 # seconds to wait for the output file(s) of a job after the job finishes
printshellcmds: True
rerun-incomplete: True
slurm-efficiency-report: True # set to True to generate a logfile of CPU and memory utilization

# Resources for each job/rule
default-resources:
    runtime: "12h" # integer defining minutes or string defining a time span (number followed by a unit, where
                   # unit is one of ms, s, m, h, d, w, y for seconds, minutes, hours, days, and years, respectively)
    mem_mb: 10000
set-resources:
    split_fastq:
        runtime: "48h"
    compress_fastq:
        runtime: "48h"
    merge_dpm:
        runtime: "24h"
    merge_bpm:
        runtime: "24h"
    assign_label:
        runtime: "24h"
    splitbam_counts:
        runtime: "24h"

# SLURM executor plugin options
slurm-logdir: "results/logs/slurm"
slurm-delete-logfiles-older-than: -1 # number of days to retain SLURM logs
slurm-keep-successful-logs: True
